openapi: 3.0.0
info:
  title: TODO API
  description: |
    TODO API for tecchu11.
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: local
    variables:
      port:
        default: '8080'
paths:
  /health:
    $ref: ./paths/health/index.yml
  /tasks:
    $ref: ./paths/tasks/index.yml
  /tasks/{TaskID}:
    $ref: ./paths/tasks/[taskID]/index.yml
components:
  schemas:
    Error:
      $ref: ./components/schemas/Error.yml
    TaskContent:
      $ref: ./components/schemas/TaskContent.yml
    Simple:
      $ref: ./components/schemas/Simple.yml
    Task:
      $ref: ./components/schemas/Task.yml
  parameters:
    Limit:
      $ref: ./components/parameters/Limit.yml
    Next:
      $ref: ./components/parameters/Next.yml
    TaskID:
      $ref: ./components/parameters/TaskID.yml
  requestBodies:
    RequestTask:
      $ref: ./components/requestBodies/RequestTask.yml
  responses:
    Response400:
      $ref: ./components/responses/Response400.yml
    Response404:
      $ref: ./components/responses/Response404.yml
    Response500:
      $ref: ./components/responses/Response500.yml
    ResponseHealthCheck:
      $ref: ./components/responses/ResponseHealthCheck.yml
    ResponseTask:
      $ref: ./components/responses/ResponseTask.yml
    ResponseTaskID:
      $ref: ./components/responses/ResponseTaskID.yml
    ResponseTasks:
      $ref: ./components/responses/ResponseTasks.yml
