services:
  app:
    image: golang:1.23rc2
    volumes:
      - .:/app
      - gomods:/go/pkg/mod
      - gobins:/go/bin
      - gocache:/root/.cache/go-build
    stdin_open: true
    tty: true
  maindb:
    image: mysql:8.0.36
    platform: linux/amd64
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/volumes/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqllib:/var/lib/mysql
    ports:
      - "13306:3306"
  localstack:
    image: localstack/localstack:3.6
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - s3-website.localhost.localstack.cloud
          - my-bucket.s3.localhost.localstack.cloud
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559" 
    environment:
      - DEBUG=1
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.socket:/var/run/docker.socket
volumes:
  gomods:
  gobins:
  gocache:
  mysqllib:
  localstack:
