services:
  app:
    image: golang:1.23.3
    environment:
      - GOPRIVATE=github.com/tecchu11
    volumes:
      - .:/app
      - go:/go
      - cache:/root/.cache
      - gh-config:/root/.config/gh
    stdin_open: true
    tty: true
  maindb:
    image: mysql:8.0.36
    platform: linux/amd64
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./testdata/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./testdata/mysql/init://docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  migration:
    build: 
      context: .
      dockerfile: ./cmd/migration/Dockerfile
    env_file:
      - .env
    depends_on:
      maindb:
        condition: service_healthy
        restart: true
  dbschema:
    build: 
      context: doc/dbschema
      network: host
      no_cache: true
    depends_on:
      migration:
        condition: service_completed_successfully
        restart: true
    ports:
      - "18000:8000"
  localstack:
    image: localstack/localstack:3.8
    networks:
      default:
        aliases:
          - localhost.localstack.cloud
          - s3.localhost.localstack.cloud
          - s3-website.localhost.localstack.cloud
          - my-bucket.s3.localhost.localstack.cloud
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559" 
    environment:
      - DEBUG=1
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.socket:/var/run/docker.socket
  auth:
    image: keycloak/keycloak:26.0.5
    env_file: .env
    command:
      - start-dev
    ports:
      - "18080:18080"
    volumes:
      - auth:/opt/keycloak/data
    depends_on:
      maindb:
        condition: service_healthy
        restart: true
volumes:
  go:
  cache:
  gh-config:
  mysql:
  localstack:
  auth:
  schemadoc:
