version: '3'

services:
  app:
    image: golang:1.23rc2
    volumes:
      - .:/app
      - gomods:/go/pkg/mod
      - gobins:/go/bin
    stdin_open: true
    tty: true
  maindb:
    image: mysql:8.0.36
    platform: linux/amd64
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/volumes/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqllib:/var/lib/mysql
    ports:
      - "13306:3306"

volumes:
  gomods:
  gobins:
  mysqllib:
