openapi: 3.0.0
info:
  title: TODO API
  description: |
    TODO API for tecchu11.
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: local
    variables:
      port:
        default: '8080'
paths:
  /health:
    $ref: paths/health.yml
  /tasks:
    $ref: paths/tasks.yml
  /tasks/{taskId}:
    $ref: paths/tasks_{taskId}.yml
  /users:
    $ref: paths/users.yml
  /users/me:
    $ref: paths/users_me.yml
