// Code generated by sqlc. DO NOT EDIT.

package maindb

import (
	"time"
)

type Task struct {
	// id is task id
	ID string
	// content is task content
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
