app_name: go-playground
server:
  address: ":8080"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
auth:
  - name: tecchu11(ADMIN)
    role: ADMIN
    key: admin
  - name: tecchu11(USER)
    role: USER
    key: user
