name: Build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: go-playground-api

jobs:
  evaluate:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.evaluate-env.outputs.name }}
    steps:
      - name: evaluate env
        id: evaluate-env
        shell: bash
        env:
          isDev: ${{ contains(github.ref, 'dev') }}
        run: |
          if $isDev; then
            echo "name=dev" >> "$GITHUB_OUTPUT"
          else
            echo "name=prd" >> "$GITHUB_OUTPUT"
          fi
      - name: show env name
        shell: bash
        run: echo ${{ steps.evaluate-env.outputs.name }}
          
  build:
    runs-on: ubuntu-latest
    needs: evaluate
    if: needs.evaluate.outputs.env_name == 'prd'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
