name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  diff-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0-rc.2"
      - name: fmt, tidy and generate
        run: |
          go fmt ./...
          go mod tidy
          go generate -tags tools ./...
      - name: check diff
        id: check-diff
        run: git diff --name-only --exit-code
        continue-on-error: true
      - name: commit and push on diff
        if: steps.check-diff.outcome == 'failure'
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'apply go mod tidy'
          git push
  test:
    runs-on: ubuntu-latest
    needs: ['diff-check']
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0-rc.2"
      - name: test
        run: |
          go test ./... --race -v -cover
