name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GOPRIVATE: github.com/tecchu11

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-go
        with:
          go-version-file: go.mod

      - name: install tools
        working-directory: ./tools
        run: go install tool

      - name: install redocly
        run: make install-tools-redoc
          
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: ./.github/actions/set-gitconfig-url
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: fmt, generate and tidy
        if: github.event_name == 'pull_request'
        run: |
          go fmt ./...
          go generate --tags oapi ./...
          go generate --tags sqlc ./...
          go mod tidy

      - name: check diff
        if: github.event_name == 'pull_request'
        id: check-diff
        run: git diff --name-only --exit-code
        continue-on-error: true

      - name: commit and push on diff
        if: steps.check-diff.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'commit diff from CI'
          git push
      
      - name: lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          only-new-issues: true

      - name: test
        run: go test ./... --race -v -cover
      
      - name: build
        run: go build ./cmd/api
        
      - uses: ./.github/actions/unset-gitconfig-url
        if: always()
        with:
          token: ${{ steps.app-token.outputs.token }}
