name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GOPRIVATE: github.com/tecchu11

jobs:
  diff-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0-rc.2"
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: ./.github/actions/set-gitconfig-url
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: fmt, tidy and generate
        run: |
          go fmt ./...
          go mod tidy
          go generate -tags tools ./...
      - name: check diff
        id: check-diff
        run: git diff --name-only --exit-code
        continue-on-error: true
      - name: commit and push on diff
        if: steps.check-diff.outcome == 'failure'
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'go diff'
          git push
      - uses: ./.github/actions/unset-gitconfig-url
        if: always()
        with:
          token: ${{ steps.app-token.outputs.token }}
  test:
    runs-on: ubuntu-latest
    needs: ['diff-check']
    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0-rc.2"
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: ./.github/actions/set-gitconfig-url
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: test
        run: go test ./... --race -v -cover
      - uses: ./.github/actions/unset-gitconfig-url
        if: always()
        with:
          token: ${{ steps.app-token.outputs.token }}
