name: renovate
run-name: CI for renovate
on:
  pull_request:

jobs:
  go-sum:
    if: startsWith(github.head_ref, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go mod tidy
      - id: check-diff
        run: git diff --exit-code
        continue-on-error: true
      - run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'apply go mod tidy'
          git push
        if: steps.check-diff.outcome == 'failure'
